# build script for dedis/crypto libraries
language: go
before_script:
    - git remote add production https://github.com/DeDiS/crypto.git
    - git fetch -a production
    - go get github.com/dyv/dedis-ci-script
script: dedis-ci-script
