language: go

install:
  - go get -t ./...
  - go get github.com/dedis/Coding || true

script:
  - make test
  # This takes the GH_TOKEN and OTHER_REPO env variables from the encrypted ones below.
  - ../Coding/bin/start-other-travis

notifications:
  email: false

env:
  global:
  - secure: bo06OwYA7ajMINQDyrMMXXAazmyRyPYKmvNJhT5NiGhV2M7F0vFVS1gA1woNzLOkOHoLRgz4o0LkBDqu42vdC1QO3RZDiCGXcM+yZ7ApTCdF/30dxRBKNKu5mfB/ZiX7grlodx2n0vp79k1lLKgmWllYxdp+j4Ylm0MJPqhY2uyxRrpuVB24QfI+QIVj5EG8wNjAzDu/CuonVjCYejA4WjtWYe5UCmIT74qp5mVL4+jqNx9iGm0lhTOu8kirIaGKJBIuB8S9eXaCMWcmpvhiUrQA6j+bjkdtKp7+c5gJbs7qy3fFd0xQJzhgcmwu53xj4FRim67FBXWCiKVbO/nW6cHBzBD24NY5GM/rHiO+vXjybYjJqTtFR2I7yPTST/AXzmQ1lfuVkrssQvs34I8xQ4yTGiLHORShGf9/4icPPO8kkFTy8283Js6yqC325cR9RGBy3Vwu+hMN2AcHq95Sfp2bGTsyVzoi4rWJtd2pqORm0r9SYiq5lrbr4P3B53OAO2tZJUq8S4eKGSzPektUPWkzy/ye5GHQBcO1jEHx61Vs9qBiomiuUWKfSGovwAzdqoVYM2qG/SeEa58l7vkvptb1/lgwRdSOl3b7916TONp3UdMCUwWGvqRCZZJJbh9jhlz7S+J9Cfg4YYlLwNBxGBXINjnMDg/XI5dXQ9vQWt8=
  - secure: E0PMgJV7JFKVrodC1q7SHPHSRVxJck7+i+LKAmK/MMNPxhMNhNMhzjN4vkkzYs3j2hmxWbpFyb68W7jUGNtxeTaJp9GQVqsmsqqoxjk39xJ5CIrblH9K3PN9ktSs1S9HZASikMHiFv6CKEbQPbM3Y9StpNlWr2pM0NsmY6NWJfAi9hiZbuDuR1/VQ23zH8fEs/qikzgQ8LMxoU4ZSW+n7UAzai0DBWK5Md8t6ja50kNPxGF5IIKc83izfO42gZk2hG5CnQSB29zhsvOohkeLiqI70pIFjwP7X9rw8OIGpO4ckaS8/UfiffqkCegYGRTrTvxV/5fMhD/4NQh8aVSjv9pcE/dH0TlKuYbGJVLwOV0wPFZsA/YN1KB28hG2R1QoKBwiUACzBQQQpoGijPME0Hqn1fPPrGiqr0josf8Y5Y/DCkq2CdbTujf9Wb+S+eo5GpfxRvWJsZvHcvpvmJ0UwKEBfXz6h+YSvnFqqSWSvOBSFjgFY89VmZG1hWUHCXnoebDP5uguKrC9Vyh17AIPtfj8z3UAfziPBwTxtUfF/FheMu0Ws/pb8cz4aDC+cBskznwVy/lPK3Nsaz/KXKbPgaYA3HnQBNsNrFzJnfJUdU66oMqhHCHrzDgMaZPq8fZk2FPvliwx6WVmo5yHjAXV1vE65VoaxKA9A5KK95ALeg0=
